/*
 *  ircd-phatbox: An IRC daemon.
 *  unicode_tables.h: Internal API for generated Unicode table lookups.
 *
 *  These functions are implemented in src/unicode_tables.c (generated by
 *  tools/gen_unicode_tables.py) and used by src/unicode_algo.c which
 *  contains the hand-written algorithm functions (NFC, skeleton, PRECIS).
 *
 *  Copyright (C) 2026 ircd-phatbox development team
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301
 *  USA
 */

#ifndef INCLUDED_unicode_tables_h
#define INCLUDED_unicode_tables_h

#include <stdint.h>

/*
 * Look up canonical decomposition for a codepoint (table only, no Hangul).
 *
 * Writes decomposed codepoint(s) to out (up to outmax).
 * Returns the number of codepoints written, or 0 if no decomposition exists,
 * or -1 on overflow.
 */
int unicode_lookup_decomp(uint32_t cp, uint32_t *out, int outmax);

/*
 * Look up canonical composition for a pair (table only, no Hangul).
 *
 * Returns the composed codepoint, or 0 if no composition exists.
 */
uint32_t unicode_lookup_comp(uint32_t cp1, uint32_t cp2);

#endif /* INCLUDED_unicode_tables_h */
