/*
 *  ircd-phatbox: An IRC daemon.
 *  unicode_data.h: Unicode character properties, case folding, NFC
 *                  normalization, script detection, bidi rules, and
 *                  confusable detection (UTS #39).
 *
 *  The lookup functions are implemented in src/unicode_data.c which
 *  is generated by tools/gen_unicode_tables.py from the Unicode
 *  Character Database files.
 *
 *  Copyright (C) 2026 ircd-phatbox development team
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301
 *  USA
 */

#ifndef INCLUDED_unicode_data_h
#define INCLUDED_unicode_data_h

#include <stdbool.h>
#include <stdint.h>

/* --- General Category checks --- */

/* Unicode General_Category L* (Letter) */
bool unicode_is_letter(uint32_t cp);

/* Unicode General_Category M* (Mark — combining, enclosing, spacing) */
bool unicode_is_mark(uint32_t cp);

/* Unicode General_Category Nd (Decimal_Number) */
bool unicode_is_digit(uint32_t cp);

/* Unicode General_Category property for default-ignorable detection */
bool unicode_is_default_ignorable(uint32_t cp);

/* --- Case folding --- */

/*
 * Simple Case Folding from CaseFolding.txt (status S and C entries).
 * Returns the folded codepoint, or cp unchanged if no fold exists.
 */
uint32_t unicode_casefold(uint32_t cp);

/* --- NFC normalization --- */

/*
 * Canonical Combining Class (0-254).  Returns 0 for starters.
 */
int unicode_canonical_class(uint32_t cp);

/*
 * Perform NFC normalization on a codepoint array.
 *
 * input/inlen: source codepoint array and its length.
 * output/outmax: destination buffer and its capacity.
 *
 * Returns the number of codepoints written, or -1 on overflow.
 */
int unicode_nfc(const uint32_t *input, int inlen, uint32_t *output, int outmax);

/* --- Script property --- */

/*
 * Script constants.  SCRIPT_COMMON and SCRIPT_INHERITED are special:
 * they are compatible with any script for single-script enforcement.
 */
#define SCRIPT_COMMON    0
#define SCRIPT_INHERITED 1
/* Remaining script values are generated — see unicode_data.c */

int unicode_script(uint32_t cp);

/* --- Bidi --- */

/*
 * Bidi_Class values needed for RFC 5893 (IDNA bidi rule).
 */
#define BIDI_L   0   /* Left-to-Right */
#define BIDI_R   1   /* Right-to-Left */
#define BIDI_AL  2   /* Arabic Letter */
#define BIDI_AN  3   /* Arabic Number */
#define BIDI_EN  4   /* European Number */
#define BIDI_ES  5   /* European Separator */
#define BIDI_CS  6   /* Common Separator */
#define BIDI_ET  7   /* European Terminator */
#define BIDI_ON  8   /* Other Neutral */
#define BIDI_BN  9   /* Boundary Neutral */
#define BIDI_NSM 10  /* Nonspacing Mark */

int unicode_bidi_class(uint32_t cp);

/*
 * Check RFC 5893 bidi rule on a codepoint array.
 * Returns true if the label satisfies the rule.
 */
bool unicode_check_bidi(const uint32_t *cps, int len);

/* --- Width mapping --- */

/*
 * Map fullwidth characters to their ASCII equivalents (PRECIS).
 * Returns the mapped codepoint, or cp unchanged if no mapping exists.
 */
uint32_t unicode_width_map(uint32_t cp);

/* --- UTS #39 Confusable detection --- */

/*
 * Apply confusable mapping to a single codepoint.
 * Writes mapped codepoint(s) to out (up to outmax).
 * Returns the number of codepoints written.
 * Returns 0 if no mapping exists (caller should use cp as-is).
 */
int unicode_confusable_map(uint32_t cp, uint32_t *out, int outmax);

/*
 * Compute the UTS #39 skeleton of a codepoint string.
 * Algorithm: NFD → strip default-ignorables → confusable map → NFD.
 *
 * Returns the number of codepoints written, or -1 on overflow.
 */
int unicode_skeleton(const uint32_t *input, int inlen,
		     uint32_t *output, int outmax);

/* --- PRECIS profile --- */

/*
 * Apply the RFC 8265 UsernameCaseMapped profile to a UTF-8 nick string.
 * Pipeline: width map → NFC → category filter → case fold → bidi check.
 *
 * On success, writes the prepared codepoints to output and returns
 * the number of codepoints written.  On failure (invalid input,
 * prohibited characters, bidi violation), returns -1.
 */
int precis_prepare_nick(const char *input, uint32_t *output, int outmax);

#endif /* INCLUDED_unicode_data_h */
